<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Current Inc.</title>
<meta name="description" content="Whether you need warmth, cool, light or water, we have what you need at prices you can afford. At Current, Inc., our goal is to provide you with courteous, expedient, professional service of the highest caliber." />
<meta name="keywords" content="west plains water furnace, water furnace, york heating and air conditioning, west plains air conditioning, waterfurnace, geothermal heating, electraflame, rotobrush, aprilaire, ultravation, honeywell, furnace repair, air conditioner repair, water tank repair" />
<meta name="robots" content=INDEX,FOLLOW" />
<meta name="GOOGLEBOT" content=INDEX,FOLLOW" />
<meta name="revisit-after" content="30 Days" />

<!--begin google tracking -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-26253305-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script><!--end google tracking -->

<link href="curr-style.css" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--
.style1 {color: #2E4B6D}
.style2 {
	color: #20324A;
	font-weight: bold;
}
-->
</style><link rel="stylesheet" href="ajxmenu.css" type="text/css" />
<script src="ajxmenu.js" type="text/javascript"></script>
</head>

<body>

<div id="wrapper">
  <div id="content">
  
    <div id="curr-header">
      <div id="curr-logo"><img src="images/logo.jpg" alt="Current Inc West Plains, MO" width="400" height="130" /></div><!--end of curr-logo -->
      
      <div id="curr-header2">
        <div align="center">
            <h2 class="style1">Your Custom Comfort Connection<br />
            Heating and Air &#8226; Electrical</h2>
          <p class="style2">417-257-0504&nbsp;&nbsp;&nbsp; 1619 Sunset Terrace &nbsp;&#8226;&nbsp; West Plains, MO 65775&nbsp; <a href="http://maps.google.com/maps?q=1619+Sunset+Terrace++West+Plains,+MO+65775&amp;hl=en&amp;sll=37.0625,-95.677068&amp;sspn=38.911557,78.662109&amp;vpsrc=0&amp;hnear=1619+Sunset+Terrace,+West+Plains,+Missouri+65775&amp;t=m&amp;z=16" target="_blank">Map us</a></p>
        </div>
      </div><!--end of curr-header2 -->
    </div>
    <!--end of curr-header -->
      
      <div id="curr-menu"><div class="AJXCSSMenueDFaTFD"><!-- AJXFILE:ajxmenu.css -->
<ul>
 <li><a href="index.php">Home</a></li>
 <li><a href="about.php">About&nbsp;Us</a></li>
 <li><a href="services.php">Services</a></li>
 <li><a href="preventive.php">Preventive&nbsp;Maintenance</a></li>
 <li><a href="comments.php">Comments</a></li>
 <li><a href="legal.php">Legal</a></li>
 <li><a href="contact.php">Contact&nbsp;Us</a></li>
</ul>
 <br />
</div>
      </div><!--end of curr-menu -->
      
        
    
    <div id="curr-main">
      <p>main</p>
    </div><!--end of curr-main -->
    
    <div id="curr-footer">    <img src="logos/york-logo.gif" alt="York" width="144" height="60" border="1" />    &nbsp; <img src="logos/water-furnace.jpg" alt="Waterfurnace" width="284" height="60" border="1" /> &nbsp; <img src="logos/GeoProLogo_191x77.gif" alt="Geopro" width="191" height="60" border="1" />  &nbsp; <img src="logos/electraflame.gif" alt="Electraflame" width="149" height="60" border="1" /><br />
        <br />
        <img src="logos/rotobrush-logo.gif" alt="Rotobrush" width="150" height="60" border="1" /> &nbsp; <img src="logos/aprilaire-logo.gif" alt="Aprilaire" width="170" height="60" border="1" />&nbsp;&nbsp; <img src="logos/logo_ultravation.jpg" alt="Ultravation" width="250" height="60" border="1" />&nbsp;&nbsp; <img src="logos/honeywell_logo.gif" alt="Honeywell" width="228" height="60" border="1" /><br />
            <br />


    <!-- Generated by www.webweaver.nu -->
      <script language="JavaScript">
<!--
document.write('&copy;' );
document.write(' 2007 - ');
document.write(new Date().getFullYear());
document.write(' Currentinc.org &nbsp;&nbsp;&nbsp;&nbsp; All Rights Reserved.');
//-->
    </script>      
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="index.php">Home</a> | <a href="contact.php">Contact</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://drjdesigns.net/">Another Website Solution by DRJ Designs </a>  &nbsp;&nbsp; <a href="http://currentinc.org/cp/" target="_blank">Admin Login</a><br />
      <br />
    </div>
    <!--curr-footer -->
  </div>
</div>
</body>
</html>
